const { GoogleGenerativeAI } = require('@google/generative-ai');
const AcademicResource = require('../models/AcademicResource');
const Note = require('../models/Note');
const Pyq = require('../models/Pyq');

function isProgrammingSubject(subject) {
  const programmingKeywords = ['data structures', 'dbms', 'database', 'computer science', 'programming', 'code', 'operating systems', 'os', 'networks'];
  return programmingKeywords.some(keyword => subject.toLowerCase().includes(keyword));
}

// Generate mock Markdown responses for all 16 operations
function getSimulatedGeminiResponse(resource, operation) {
  const title = resource.title;
  const subject = resource.subject;
  const unit = resource.unit || 'All Units';

  switch (operation) {
    case 'summarize':
      return `
# 📝 AI Note Summary: ${title}
**Subject:** ${subject} | **Unit/Section:** ${unit}
*Generated by Google Gemini 1.5 Flash*

---

## 🔍 Executive Overview
This resource details foundational models inside **${subject}**. The document covers primary structural diagrams, operational axioms, and optimizations.

---

## 🔑 Core Concepts
1. **System Modularity**: Decomposing large calculations into decoupled segments speeds up execution.
2. **Resource Boundaries**: Validating inputs prevent boundary overflow logs.
3. **Caching**: Storing hot segments locally speeds up lookups by several orders of magnitude.
`;

    case 'quiz':
      return `
# ❓ Practice Quiz: ${subject}
Test your conceptual understanding.

---

### Q1: What is the main benefit of modular structures?
- A) Increased storage size
- **B) Decoupled debugging and fault isolation**
- C) Disabling network access
* **Explanation:** Modularity localizes faults so issues inside one component don't crash the whole thread.

### Q2: Which worst-case complexity represents single-nested loops dependent on size $N$?
- **A) $O(N)$ linear time**
- B) $O(N^2)$ quadratic time
- C) $O(1)$ constant time
* **Explanation:** Iterating once through a collection of size $N$ scales linearly.
`;

    case 'flashcards':
      return `
# 🎴 Flashcards: ${subject}
Use these active recall slots for exam prep.

---

## Card 1
* **Front:** Define Big-O Notation.
* **Back:** A mathematical metric representing the upper bound of execution complexity in the worst-case scenario.

---

## Card 2
* **Front:** Why do we pre-validate array indices?
* **Back:** To prevent indexing violations (out-of-bounds array reads) which cause thread crashes.
`;

    case 'viva':
      return `
# 🎙️ Viva Voce & Oral Prep: ${subject}
Oral exam questions with model answers.

---

### Q1: What is thread latency and how do you minimize it?
> **Model Answer:** Latency is the round-trip delay experienced during data requests. We minimize it by bringing records closer to execution units using caching layers.

### Q2: Explain worst-case quadratic complexity $O(N^2)$.
> **Model Answer:** It represents execution scales where time requirements grow quadratically relative to inputs, typically caused by nested loops.
`;

    case 'interview_questions':
      return `
# 💼 Interview Preparation Questions: ${subject}
Common technical interview questions asked by top firms.

---

### Q1: How do you design a thread-safe implementation of this system?
> **Answer:** We introduce concurrency controls like mutex locks to enforce mutual exclusion, preventing concurrent threads from corrupting shared states.

### Q2: What is the difference between shallow and deep copying?
> **Answer:** Shallow copying copies reference addresses only. Deep copying duplicates the underlying data record entirely, preventing shared mutation side-effects.
`;

    case 'questions':
      return `
# 🏛️ Important Exam Questions: ${subject}
Divided by marks criteria.

---

### Part A (2 Marks)
1. Write the worst-case time complexity of binary search.
2. Define the Intermediate Value Theorem.

### Part B (13 Marks)
1. Explain the architectural pipeline of distributed memory structures. Contrast it with shared caching.
`;

    case 'study_plan':
      return `
# 📅 5-Day Study Planner: ${subject}
Your target path to master this resource.

- **Day 1**: Read pages 1-10. Complete Flashcard 1.
- **Day 2**: Trace code algorithms for basic inputs.
- **Day 3**: Practice the online Quiz. Review explanations.
- **Day 4**: Write answers to Part B questions.
- **Day 5**: Conduct a timed mock viva using Card Q&As.
`;

    case 'explain_concepts':
    case 'explain_topic':
      return `
# 💡 Topic Explainer: ${title}
Plain-english breakdowns of complex items.

---

### 1. Divide and Conquer Divisions
Splitting lists into halves recursively simplifies execution. It reduces searching from linear $O(N)$ checks to logarithmic $O(\log N)$ splits.

### 2. Guard Validators
Checking inputs at the entry edge prevents invalid parameters from polluting deep operational pipelines.
`;

    case 'translate_notes':
      return `
# 🌐 Translated Notes (Spanish Fallback)
*Traducido por CampusConnect AI*

---

## Resumen Ejecutivo
Este recurso académico detalla los modelos de datos fundamentales dentro de **${subject}**. El documento cubre diagramas de flujo y optimizaciones del sistema.

### Conceptos Clave:
1. **Modularidad**: El desacoplamiento de componentes acelera el mantenimiento.
2. **Límites de memoria**: Las validaciones previenen desbordamientos de datos.
`;

    case 'pyq_analysis':
      return `
# 📊 PYQ Exam Analysis: ${subject}
Strategic statistics compiled from past exam papers.

* **Difficulty Distribution:** 20% Easy, 60% Medium, 20% Hard.
* **Core Topics Weightage:** Algorithmic logic (50%), definitions (20%), derivations (30%).
`;

    case 'repeated_questions':
      return `
# 🔄 Repeated PYQ Questions: ${subject}
High-frequency questions appearing in multiple exam cycles.

---

### 1. Mutex Concurrency (CAT1 & Model Exams - Repeated 4x)
* "Detail the synchronization issues in shared memory setups and draw state diagrams."
* **Weightage:** 13 Marks.

### 2. Time Complexity Math Proofs (Semester Exams - Repeated 3x)
* "Prove that log-linear bounds $O(N \log N)$ represent optimal sorting constraints."
* **Weightage:** 8 Marks.
`;

    case 'frequent_topics':
      return `
# 📈 Frequently Asked Topics: ${subject}
Core topics you must review before writing exams.

* **Topic 1**: Stack and Queue implementations (出现在 100% 的数据结构考试中).
* **Topic 2**: Index structuring and B-Tree balancing.
* **Topic 3**: Cache-locality and LRU eviction policies.
`;

    case 'expected_questions':
      return `
# 🔮 Expected Questions: ${subject}
Predicted questions for the upcoming exam cycle.

---

1. "Explain the Single Responsibility Principle and write a code example showing decoupled models." (Part A - Expected)
2. "Design a thread-safe generic stack container. Write capacity overflow guards." (Part B - Expected)
`;

    case 'difficulty_analysis':
      return `
# ⚖️ Difficulty Analysis Matrix: ${subject}
Breakdown of question complexities.

* **Foundational Recall (Easy):** 30% of the paper. Focuses on simple definitions (e.g. define big-O).
* **Logical Application (Medium):** 50% of the paper. Requires writing code traces or calculating intermediate variables.
* **System Design (Hard):** 20% of the paper. Requires drawing distributed systems architectures.
`;

    case 'topic_distribution':
      return `
# 🥧 Topic Mark Distribution: ${subject}
How marks are apportioned across chapters.

* **Chapter 1 (Foundations):** 15% of total marks.
* **Chapter 2 (Algorithmic Logic):** 45% of total marks.
* **Chapter 3 (System Operations):** 40% of total marks.
`;

    case 'marks_distribution':
      return `
# 🧮 Marks Distribution Scheme: ${subject}
Marking rubric for typical exam papers.

| Part | Questions | Marks per Question | Total Marks |
| --- | --- | --- | --- |
| Part A | 10 | 2 Marks | 20 Marks |
| Part B | 5 | 13 Marks | 65 Marks |
| Part C | 1 | 15 Marks | 15 Marks |
`;

    default:
      return `# AI Insights on ${title}`;
  }
}

// Main AI Generation function using Gemini
async function generateAIContent(resourceId, operation) {
  let resource = await AcademicResource.findById(resourceId);
  if (!resource) {
    const note = await Note.findById(resourceId);
    if (note) {
      resource = {
        _id: note._id,
        title: note.title,
        subject: note.subject,
        unit: note.unit || '',
        aiIndexed: false,
        save: async () => {}, // Mock save
      };
    } else {
      const pyq = await Pyq.findById(resourceId);
      if (pyq) {
        resource = {
          _id: pyq._id,
          title: `${pyq.subject} ${pyq.examType} ${pyq.year} Question Paper`,
          subject: pyq.subject,
          unit: '',
          aiIndexed: false,
          save: async () => {}, // Mock save
        };
      }
    }
  }

  if (!resource) {
    throw new Error('Resource not found.');
  }

  const geminiApiKey = process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : '';
  const geminiModelName = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
  const isMockKey = !geminiApiKey || geminiApiKey === 'your_gemini_api_key';

  if (!isMockKey) {
    try {
      const ai = new GoogleGenerativeAI(geminiApiKey);
      const model = ai.getGenerativeModel({ model: geminiModelName });

      const prompts = {
        summarize: `Summarize "${resource.title}" (${resource.subject}) in Markdown.`,
        quiz: `Create a 5-question quiz for "${resource.title}" (${resource.subject}) in Markdown.`,
        flashcards: `Create 5 flashcards for "${resource.title}" (${resource.subject}) in Markdown.`,
        viva: `Provide 5 viva questions for "${resource.title}" (${resource.subject}) in Markdown.`,
        interview_questions: `List 5 technical interview questions related to "${resource.title}" (${resource.subject}) in Markdown.`,
        questions: `List important semester exam questions for "${resource.title}" (${resource.subject}) in Markdown.`,
        study_plan: `Create a study plan for "${resource.title}" (${resource.subject}) in Markdown.`,
        explain_concepts: `Explain core concepts of "${resource.title}" (${resource.subject}) in Markdown.`,
        explain_topic: `Explain core concepts of "${resource.title}" (${resource.subject}) in Markdown.`,
        translate_notes: `Translate summary of "${resource.title}" (${resource.subject}) to Spanish in Markdown.`,
        pyq_analysis: `Provide a PYQ analysis of "${resource.title}" (${resource.subject}) in Markdown.`,
        repeated_questions: `List repeated questions in "${resource.title}" (${resource.subject}) in Markdown.`,
        frequent_topics: `List frequently asked topics in "${resource.title}" (${resource.subject}) in Markdown.`,
        expected_questions: `List expected exam questions in "${resource.title}" (${resource.subject}) in Markdown.`,
        difficulty_analysis: `Analyze question difficulty in "${resource.title}" (${resource.subject}) in Markdown.`,
        topic_distribution: `Analyze topic marks distribution in "${resource.title}" (${resource.subject}) in Markdown.`,
        marks_distribution: `Detail marks distribution in "${resource.title}" (${resource.subject}) in Markdown.`,
      };

      const prompt = prompts[operation] || `Analyze the resource "${resource.title}" and return academic insights.`;
      
      const result = await model.generateContent(prompt);
      const response = await result.response;
      let text = response.text();
      
      if (!resource.aiIndexed) {
        resource.aiIndexed = true;
        await resource.save();
      }

      return text;
    } catch (apiError) {
      console.warn(`[Gemini API] Failed. Falling back to simulation. Error: ${apiError.message}`);
      return getSimulatedGeminiResponse(resource, operation);
    }
  } else {
    const mockText = getSimulatedGeminiResponse(resource, operation);
    if (!resource.aiIndexed) {
      resource.aiIndexed = true;
      await resource.save();
    }
    return mockText;
  }
}

async function chat(history, message, systemPersona) {
  const geminiApiKey = process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : '';
  const geminiModelName = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
  const isMockKey = !geminiApiKey || geminiApiKey === 'your_gemini_api_key';

  if (!isMockKey) {
    try {
      const ai = new GoogleGenerativeAI(geminiApiKey);
      const model = ai.getGenerativeModel({ model: geminiModelName });
      
      const chatSession = model.startChat({
        history: history.map(h => ({
          role: h.role === 'user' ? 'user' : 'model',
          parts: [{ text: h.content || h.parts || h.text || '' }]
        })),
        systemInstruction: { parts: [{ text: systemPersona }] }
      });

      const result = await chatSession.sendMessage(message);
      const response = await result.response;
      return response.text();
    } catch (apiError) {
      console.warn(`[Gemini Chat API] Failed. Falling back to mock response. Error: ${apiError.message}`);
      return `[Mock AI Assistant Mode] I received your message: "${message}". In simulation mode, I can help you revise. Set a valid GEMINI_API_KEY in the environment for live AI responses.`;
    }
  } else {
    return `[Mock AI Assistant Mode] Thank you for asking about "${message}". Set a valid GEMINI_API_KEY in the backend configuration to activate live Gemini AI answers.`;
  }
}

async function generateJSON(systemInstruction, userPrompt) {
  const geminiApiKey = process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : '';
  const geminiModelName = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
  const isMockKey = !geminiApiKey || geminiApiKey === 'your_gemini_api_key';

  if (!isMockKey) {
    try {
      const ai = new GoogleGenerativeAI(geminiApiKey);
      const model = ai.getGenerativeModel({
        model: geminiModelName,
        generationConfig: { responseMimeType: "application/json" }
      });
      const result = await model.generateContent(`${systemInstruction}\n\nUser Input:\n${userPrompt}`);
      const response = await result.response;
      return JSON.parse(response.text());
    } catch (apiError) {
      console.warn(`[Gemini JSON API] Failed. Falling back to mock generator. Error: ${apiError.message}`);
      return getMockJSONResponse(systemInstruction, userPrompt);
    }
  } else {
    return getMockJSONResponse(systemInstruction, userPrompt);
  }
}

function getMockJSONResponse(systemInstruction, userPrompt) {
  const instr = systemInstruction.toLowerCase();
  const prompt = userPrompt.toLowerCase();

  if (instr.includes('summarize') || instr.includes('summary')) {
    return {
      summary: "This resource details software components, data boundary check requirements, and concurrency configurations.",
      keyPoints: [
        "Pre-validating boundaries checks limits at the interface layer.",
        "Decoupled components localize faults and prevent cascade failures.",
        "Asynchronous state updates keep transaction updates synchronized."
      ]
    };
  }

  if (instr.includes('quiz')) {
    return {
      questions: [
        {
          question: "Which data structure follows a Last-In, First-Out (LIFO) pattern?",
          options: ["Queue", "Stack", "Binary Tree", "Hash Table"],
          correctAnswerIndex: 1,
          explanation: "Stacks insert and delete elements at the same end, matching LIFO constraints."
        },
        {
          question: "What does atomic execution mean in concurrency?",
          options: ["Runs in parallel threads", "Performs fully or not at all without interference", "Splits instructions into smaller variables", "Compiles code dynamically"],
          correctAnswerIndex: 1,
          explanation: "An atomic operation is indivisible; other threads see it as either completed or not started."
        }
      ]
    };
  }

  if (instr.includes('viva') || instr.includes('oral')) {
    return {
      questions: [
        {
          question: "Explain the difference between call-by-value and call-by-reference.",
          modelAnswer: "Call-by-value passes a copy of the actual parameter, protecting it from side-effects. Call-by-reference passes address references, enabling modifications to propagate outside the function scope."
        }
      ]
    };
  }

  if (instr.includes('pyq') || instr.includes('question pattern')) {
    return {
      likelyImportantTopics: [
        "Dynamic Programming vs Divide & Conquer",
        "Resource locking and Deadlock conditions"
      ],
      examPatternInsights: "Exams focus heavily on short definitions (Part A) and systems design derivations (Part B).",
      recommendation: "Focus revision on drawing accurate database index structures and state machines."
    };
  }

  if (instr.includes('interview') || instr.includes('job interview')) {
    return {
      technicalQuestions: [
        "What are ACID transactions in relational databases?",
        "Explain memory pagination policies and thrashing bounds."
      ],
      hrQuestions: [
        "Describe a time when you received constructive feedback on your code.",
        "How do you prioritize deliverables when deadlines are tight?"
      ],
      tips: [
        "Identify the time and space constraints before proposing your solution.",
        "Ask clarifying questions about scaling and input types first."
      ]
    };
  }

  if (instr.includes('roadmap') || instr.includes('learning roadmap')) {
    return {
      title: "Full-Stack Software Architecture learning path",
      steps: [
        {
          phase: "Stage 1: Frontend foundations",
          topics: ["DOM Operations", "State Management hooks"],
          resources: ["React Official Documentation", "MDN Web Docs"]
        }
      ]
    };
  }

  if (instr.includes('plan') || instr.includes('study planner') || instr.includes('schedule')) {
    return {
      schedule: [
        { day: "Day 1-2", topicsToCover: ["Core Algorithms", "Time Complexity math proofs"], hours: 4 },
        { day: "Day 3-5", topicsToCover: ["Practice Exam questions", "Self-Assessment MCQs"], hours: 3 }
      ],
      tips: [
        "Solve quizzes to test knowledge intervals.",
        "Form study groups to verbally explain answers."
      ]
    };
  }

  if (instr.includes('explain') || instr.includes('code snippet')) {
    return {
      language: "JavaScript / TypeScript",
      explanation: "This snippet establishes database connections and mounts route controllers safely with try-catch verification blocks.",
      complexity: { time: "O(1)", space: "O(1)" },
      keyTakeaways: [
        "Safe error boundary handling prevents system crashes.",
        "Synchronizes database client state on startup."
      ]
    };
  }

  if (instr.includes('debug') || instr.includes('bugs')) {
    return {
      hasBugs: true,
      bugs: [
        {
          line: 5,
          issue: "Missing empty list check",
          fix: "Add list validation bounds checking to prevent undefined index reads."
        }
      ],
      correctedCode: "function verify(arr) { if (!arr || arr.length === 0) return null; }"
    };
  }

  if (instr.includes('flashcard')) {
    return {
      flashcards: [
        { front: "Big-O search bounds of Balanced BST", back: "O(log N)" },
        { front: "What is deadlock?", back: "A state where threads wait indefinitely for resources locked by each other." }
      ]
    };
  }

  if (instr.includes('notes') || instr.includes('study notes')) {
    return {
      subject: "Operating Systems",
      topic: "Concurrencies",
      introduction: "Concurrency represents the simultaneous execution of multiple computing threads.",
      sections: [
        {
          heading: "Race Conditions",
          content: "Race conditions arise when concurrent threads modify shared states without synchronization blocks."
        }
      ],
      summary: "Mutexes ensure shared data access safety."
    };
  }

  if (instr.includes('resume') || instr.includes('ats')) {
    return {
      score: 85,
      suggestions: [
        "Quantify project achievements with percentages or speed metrics.",
        "Add relevant industry keywords like MERN, Git, and Docker."
      ],
      atsKeywords: ["Full-Stack Development", "Agile methodologies", "RESTful APIs"]
    };
  }

  return {
    status: "Simulation complete",
    data: "Mock results generated by CampusConnect AI engines."
  };
}

module.exports = {
  generateAIContent,
  chat,
  generateJSON
};
